module OpCodes where

import DataTypes
import Data.Word
import Operations
import Data.List
import Addressing
import CPU6502

getOperation :: Word8 -> Op
getOperation opcode = case (lookup opcode opcodes) of 
                 Just o -> o
                 Nothing -> (noop, NoInputAddressing, NoOutputAddressing)

opcodes :: [(Word8, Op)]
opcodes = [(0x05, (ora, zeroPageInput, aOutput)),
           (0x06, (asl, zeroPageInput, aOutput)),
           (0x09, (ora, immediateInput, aOutput)),
           (0x0A, (asl, aInput, aOutput)),
           (0x10, (bpl, immediateInput, branchOutput)),
           (0x18, (setFlag setC False, NoInputAddressing, pOutput)),
           (0x20, (jsr, NoInputAddressing, NoOutputAddressing)),
           (0x25, (anda, zeroPageInput, aOutput)),
           (0x29, (anda, immediateInput, aOutput)),
           (0x2A, (rol, aInput, aOutput)),
           (0x2C, (bit, absoluteInput, NoOutputAddressing)),
           (0x30, (bmi, immediateInput, branchOutput)),
           (0x35, (anda, zeroPageModInput x, aOutput)),
           (0x3D, (anda, absoluteModInput x, aOutput)),
           (0x38, (setFlag setC True, NoInputAddressing, pOutput)),
           (0x40, (rti, NoInputAddressing, NoOutputAddressing)),
           (0x45, (eor, zeroPageInput, aOutput)),
           (0x46, (lsr, zeroPageInput, aOutput)),
           (0x48, (st, aInput, pushOutput)),
           (0x49, (eor, immediateInput, aOutput)),
           (0x4A, (lsr, aInput, aOutput)),
           (0x4C, (jmpAb, NoInputAddressing, NoOutputAddressing)),
           (0x60, (rts, NoInputAddressing, NoOutputAddressing)),
           (0x65, (adc, zeroPageInput, aOutput)),
           (0x66, (ror, zeroPageRegressInput, zeroPageOutput)),
           (0x68, (ld, popInput, aOutput)),
           (0x69, (adc, immediateInput, aOutput)),
           (0x6A, (ror, aInput, aOutput)),
           (0x6C, (jmpInd, NoInputAddressing, NoOutputAddressing)),
           (0x6D, (adc, absoluteInput, aOutput)),
           (0x70, (bvs, immediateInput, branchOutput)),
           (0x78, (setFlag setI True, NoInputAddressing, pOutput)),
           (0x7E, (ror, absoluteModRegressInput x, absoluteModOutput x)),
           (0x84, (st, yInput, zeroPageOutput)),
           (0x85, (st, aInput, zeroPageOutput)),
           (0x86, (st, xInput, zeroPageOutput)),
           (0x88, (dec, yInput, yOutput)),
           (0x8A, (tx, xInput, aOutput)),
           (0x8C, (st, yInput, absoluteOutput)),
           (0x8D, (st, aInput, absoluteOutput)),
           (0x8E, (st, xInput, absoluteOutput)),
           (0x90, (bcc, immediateInput, branchOutput)),
           (0x91, (st, aInput, indirectYOutput)),
           (0x95, (st, aInput, zeroPageModOutput x)),
           (0x98, (tx, yInput, aOutput)),
           (0x99, (st, aInput, absoluteModOutput y)),
           (0x9A, (tx, xInput, spOutput)),
           (0x9D, (st, aInput, absoluteModOutput x)),
           (0xA0, (ld, immediateInput, yOutput)),
           (0xA2, (ld, immediateInput, xOutput)),
           (0xA4, (ld, zeroPageInput, yOutput)),
           (0xA5, (ld, zeroPageInput, aOutput)),
           (0xA6, (ld, zeroPageInput, xOutput)),
           (0xA8, (tx, aInput, yOutput)),
           (0xA9, (ld, immediateInput, aOutput)),
           (0xAA, (tx, aInput, xOutput)),
           (0xAC, (ld, absoluteInput, yOutput)),
           (0xAD, (ld, absoluteInput, aOutput)),
           (0xAE, (ld, absoluteInput, xOutput)),
           (0xB0, (bcs, immediateInput, branchOutput)),
           (0xB1, (ld, indirectYInput, aOutput)),
           (0xB4, (ld, zeroPageInput, yOutput)),
           (0xB5, (ld, zeroPageModInput x, aOutput)),
           (0xB9, (ld, absoluteModInput y, aOutput)),
           (0xBD, (ld, absoluteModInput x, aOutput)),
           (0xBE, (ld, absoluteModInput y, xOutput)),
           (0xC0, (cmp y, immediateInput, NoOutputAddressing)),
           (0xC6, (dec, zeroPageRegressInput, zeroPageOutput)),
           (0xC8, (inc, yInput, yOutput)),
           (0xC9, (cmp a, immediateInput, NoOutputAddressing)),
           (0xCA, (dec, xInput, xOutput)),
           (0xCE, (dec, absoluteRegressInput, absoluteOutput)), 
           (0xD0, (bne, immediateInput, branchOutput)),
           (0xD6, (dec, zeroPageModRegressInput x, zeroPageModOutput x)),
           (0xD8, (setFlag setD False, NoInputAddressing, pOutput)),
           (0xE0, (cmp x, immediateInput, NoOutputAddressing)),
           (0xE5, (sbc, zeroPageInput, aOutput)),
           (0xE6, (inc, zeroPageRegressInput, zeroPageOutput)),
           (0xE8, (inc, xInput, xOutput)),
           (0xE9, (sbc, immediateInput, aOutput)),
           (0xEE, (inc, absoluteRegressInput, absoluteOutput)),
           (0xF0, (beq, immediateInput, branchOutput)),
           (0xF9, (sbc, absoluteModInput y, aOutput))]
